# Generated by Django 4.2.3 on 2023-07-31 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoversationMessage',
            new_name='ConversationMessage',
        ),
    ]
